### PR TITLE
New resources

### PR DESCRIPTION
**Pull request by ubaldop**
Hi there,
that's the first PR for your repository :smile: I am glad to add **FutureLearn** to the list. There I attended few MOOCs about Erlang.  
Also, they offer a course on Haskell too.

Moreover, I fixed few minor typos in the content of README.md.

### CODE REVIEW

**Comment by Eomm** [comment]
Thank you @P3trur0 

I would propose:
+ let's define an icon for "freemium" and not 2 icons because I could understand that some courses are free, and other are paid. I shell use ✂️ because it's free and they "cut" some functionalities from the "pro" version. What do you think or propose?
+ in the columns I would add only icons and no text 

(I will add this considerations in the _contribute_ section)

Let me know 😄

**Comment by ubaldop** [comment]
@Eomm ok then, it sounds good to me about scissors emoji. I'll submit an updated version of my PR in minutes.

However, about the missing text in the table itself, my opinion is that when the table starts to increase its size, it could look like a big set of emojis and it could be difficult to figure out the purpose of the single row. About that, did you consider to add a final column named, e.g. "notes", where you can write some comments about the single study platform?

**Comment by ubaldop** [comment]
@Eomm PR updated! Please, check it out :)

**Comment by Eomm** [comment]
Thank you very much 👍

**Pull request merged**
